export const PHONE_CODES = [
    { code: "+93", country: "AF", label: "Afghanistan (+93)", mask: "7xxxxxxxx" },
    { code: "+355", country: "AL", label: "Albania (+355)", mask: "6xxxxxxxx" },
    { code: "+213", country: "DZ", label: "Algeria (+213)", mask: "xxxxxxxx" },
    { code: "+1-684", country: "AS", label: "American Samoa (+1-684)", mask: "xxxxxxxxx" },
    { code: "+376", country: "AD", label: "Andorra (+376)", mask: "xxxxxxxxx" },
    { code: "+244", country: "AO", label: "Angola (+244)", mask: "9xxxxxxxx" },
    { code: "+1-264", country: "AI", label: "Anguilla (+1-264)", mask: "xxxxxxxxx" },
    { code: "+672", country: "AQ", label: "Antarctica (+672)", mask: "xxxxxxxxx" },
    { code: "+1-268", country: "AG", label: "Antigua and Barbuda (+1-268)", mask: "xxxxxxxxx" },
    { code: "+54", country: "AR", label: "Argentina (+54)", mask: "9xxxxxxxxx" },
    { code: "+374", country: "AM", label: "Armenia (+374)", mask: "xx xxxxxx" },
    { code: "+297", country: "AW", label: "Aruba (+297)", mask: "xxxxxxxxx" },
    { code: "+61", country: "AU", label: "Australia (+61)", mask: "4xxxxxxxx" },
    { code: "+43", country: "AT", label: "Austria (+43)", mask: "xxxxxxxxxx" },
    { code: "+994", country: "AZ", label: "Azerbaijan (+994)", mask: "xx xxxxxx" },
    { code: "+1-242", country: "BS", label: "Bahamas (+1-242)", mask: "xxxxxxxxx" },
    { code: "+973", country: "BH", label: "Bahrain (+973)", mask: "xxxxxxxx" },
    { code: "+880", country: "BD", label: "Bangladesh (+880)", mask: "1xxxxxxxxx" },
    { code: "+1-246", country: "BB", label: "Barbados (+1-246)", mask: "xxxxxxxxx" },
    { code: "+375", country: "BY", label: "Belarus (+375)", mask: "xx xxxxxx" },
    { code: "+32", country: "BE", label: "Belgium (+32)", mask: "4xxxxxxxx" },
    { code: "+501", country: "BZ", label: "Belize (+501)", mask: "xxxxxxxxx" },
    { code: "+229", country: "BJ", label: "Benin (+229)", mask: "xx xxxxxx" },
    { code: "+1-441", country: "BM", label: "Bermuda (+1-441)", mask: "xxxxxxxxx" },
    { code: "+975", country: "BT", label: "Bhutan (+975)", mask: "xxxxxxxxx" },
    { code: "+591", country: "BO", label: "Bolivia (+591)", mask: "xxxxxxxxx" },
    { code: "+387", country: "BA", label: "Bosnia and Herzegovina (+387)", mask: "xx xxxxxx" },
    { code: "+267", country: "BW", label: "Botswana (+267)", mask: "xxxxxxxxx" },
    { code: "+55", country: "BR", label: "Brazil (+55)", mask: "11 xxxxxxxx" },
    { code: "+246", country: "IO", label: "British Indian Ocean Territory (+246)", mask: "xxxxxxxxx" },
    { code: "+1-284", country: "VG", label: "British Virgin Islands (+1-284)", mask: "xxxxxxxxx" },
    { code: "+673", country: "BN", label: "Brunei (+673)", mask: "xxxxxxxxx" },
    { code: "+359", country: "BG", label: "Bulgaria (+359)", mask: "xxxxxxxxxx" },
    { code: "+226", country: "BF", label: "Burkina Faso (+226)", mask: "xxxxxxxx" },
    { code: "+257", country: "BI", label: "Burundi (+257)", mask: "xxxxxxxxx" },
    { code: "+855", country: "KH", label: "Cambodia (+855)", mask: "xx xxxxxx" },
    { code: "+237", country: "CM", label: "Cameroon (+237)", mask: "xxxxxxxxx" },
    { code: "+1", country: "CA", label: "Canada (+1)", mask: "xxxxxxxxxx" },
    { code: "+238", country: "CV", label: "Cape Verde (+238)", mask: "xxxxxxxxx" },
    { code: "+1-345", country: "KY", label: "Cayman Islands (+1-345)", mask: "xxxxxxxxx" },
    { code: "+236", country: "CF", label: "Central African Republic (+236)", mask: "xxxxxxxxx" },
    { code: "+235", country: "TD", label: "Chad (+235)", mask: "xxxxxxxxx" },
    { code: "+56", country: "CL", label: "Chile (+56)", mask: "9 xxxxxxxx" },
    { code: "+86", country: "CN", label: "China (+86)", mask: "1xx xxxxxxxx" },
    { code: "+61", country: "CX", label: "Christmas Island (+61)", mask: "xxxxxxxxx" },
    { code: "+61", country: "CC", label: "Cocos (Keeling) Islands (+61)", mask: "xxxxxxxxx" },
    { code: "+57", country: "CO", label: "Colombia (+57)", mask: "3xxxxxxxxx" },
    { code: "+269", country: "KM", label: "Comoros (+269)", mask: "xxxxxxxxx" },
    { code: "+682", country: "CK", label: "Cook Islands (+682)", mask: "xxxxxxxxx" },
    { code: "+506", country: "CR", label: "Costa Rica (+506)", mask: "xxxxxxxxx" },
    { code: "+385", country: "HR", label: "Croatia (+385)", mask: "9x xxxxxx" },
    { code: "+53", country: "CU", label: "Cuba (+53)", mask: "xxxxxxxxx" },
    { code: "+599", country: "CW", label: "Curacao (+599)", mask: "xxxxxxxxx" },
    { code: "+357", country: "CY", label: "Cyprus (+357)", mask: "9xxxxxxx" },
    { code: "+420", country: "CZ", label: "Czech Republic (+420)", mask: "xxx xxx xxx" },
    { code: "+243", country: "CD", label: "Democratic Republic of the Congo (+243)", mask: "9xxxxxxxx" },
    { code: "+45", country: "DK", label: "Denmark (+45)", mask: "xxxxxxxx" },
    { code: "+253", country: "DJ", label: "Djibouti (+253)", mask: "xxxxxxxxx" },
    { code: "+1-767", country: "DM", label: "Dominica (+1-767)", mask: "xxxxxxxxx" },
    { code: "+1-809", country: "DO", label: "Dominican Republic (+1-809)", mask: "xxxxxxxxx" },
    { code: "+670", country: "TL", label: "East Timor (+670)", mask: "xxxxxxxxx" },
    { code: "+593", country: "EC", label: "Ecuador (+593)", mask: "9xxxxxxxx" },
    { code: "+20", country: "EG", label: "Egypt (+20)", mask: "xxxxxxxxxx" },
    { code: "+503", country: "SV", label: "El Salvador (+503)", mask: "xxxxxxxxx" },
    { code: "+240", country: "GQ", label: "Equatorial Guinea (+240)", mask: "xxxxxxxxx" },
    { code: "+291", country: "ER", label: "Eritrea (+291)", mask: "xxxxxxxxx" },
    { code: "+372", country: "EE", label: "Estonia (+372)", mask: "xxxxxxxxx" },
    { code: "+251", country: "ET", label: "Ethiopia (+251)", mask: "9xxxxxxxx" },
    { code: "+500", country: "FK", label: "Falkland Islands (+500)", mask: "xxxxxxxxx" },
    { code: "+298", country: "FO", label: "Faroe Islands (+298)", mask: "xxxxxxxxx" },
    { code: "+679", country: "FJ", label: "Fiji (+679)", mask: "xxxxxxxxx" },
    { code: "+358", country: "FI", label: "Finland (+358)", mask: "4x xxxxxxx" },
    { code: "+33", country: "FR", label: "France (+33)", mask: "6xxxxxxxx" },
    { code: "+594", country: "GF", label: "French Guiana (+594)", mask: "xxxxxxxxx" },
    { code: "+689", country: "PF", label: "French Polynesia (+689)", mask: "xxxxxxxxx" },
    { code: "+241", country: "GA", label: "Gabon (+241)", mask: "xxxxxxxxx" },
    { code: "+220", country: "GM", label: "Gambia (+220)", mask: "xxxxxxxxx" },
    { code: "+995", country: "GE", label: "Georgia (+995)", mask: "xxxxxxxxx" },
    { code: "+49", country: "DE", label: "Germany (+49)", mask: "1xx xxxxxxx" },
    { code: "+233", country: "GH", label: "Ghana (+233)", mask: "5xxxxxxxx" },
    { code: "+350", country: "GI", label: "Gibraltar (+350)", mask: "xxxxxxxxx" },
    { code: "+30", country: "GR", label: "Greece (+30)", mask: "69xxxxxxx" },
    { code: "+299", country: "GL", label: "Greenland (+299)", mask: "xxxxxxxxx" },
    { code: "+1-473", country: "GD", label: "Grenada (+1-473)", mask: "xxxxxxxxx" },
    { code: "+1-671", country: "GU", label: "Guam (+1-671)", mask: "xxxxxxxxx" },
    { code: "+502", country: "GT", label: "Guatemala (+502)", mask: "xxxxxxxxx" },
    { code: "+44-1481", country: "GG", label: "Guernsey (+44-1481)", mask: "xxxxxxxxx" },
    { code: "+224", country: "GN", label: "Guinea (+224)", mask: "xxxxxxxxx" },
    { code: "+245", country: "GW", label: "Guinea-Bissau (+245)", mask: "xxxxxxxxx" },
    { code: "+592", country: "GY", label: "Guyana (+592)", mask: "xxxxxxxxx" },
    { code: "+509", country: "HT", label: "Haiti (+509)", mask: "xxxxxxxxx" },
    { code: "+504", country: "HN", label: "Honduras (+504)", mask: "xxxxxxxxx" },
    { code: "+852", country: "HK", label: "Hong Kong (+852)", mask: "xxxxxxxxx" },
    { code: "+36", country: "HU", label: "Hungary (+36)", mask: "20xxxxxxx" },
    { code: "+354", country: "IS", label: "Iceland (+354)", mask: "xxxxxxxxx" },
    { code: "+91", country: "IN", label: "India (+91)", mask: "9xxxxxxxxx" },
    { code: "+62", country: "ID", label: "Indonesia (+62)", mask: "8xxxxxxxxx" },
    { code: "+98", country: "IR", label: "Iran (+98)", mask: "9xxxxxxxxx" },
    { code: "+964", country: "IQ", label: "Iraq (+964)", mask: "7xxxxxxxxx" },
    { code: "+353", country: "IE", label: "Ireland (+353)", mask: "8xxxxxxxxx" },
    { code: "+44-1624", country: "IM", label: "Isle of Man (+44-1624)", mask: "xxxxxxxxx" },
    { code: "+972", country: "IL", label: "Israel (+972)", mask: "5xxxxxxxx" },
    { code: "+39", country: "IT", label: "Italy (+39)", mask: "3xxxxxxxxx" },
    { code: "+225", country: "CI", label: "Ivory Coast (+225)", mask: "xxxxxxxxx" },
    { code: "+1-876", country: "JM", label: "Jamaica (+1-876)", mask: "xxxxxxxxx" },
    { code: "+81", country: "JP", label: "Japan (+81)", mask: "90xxxxxxxx" },
    { code: "+44-1534", country: "JE", label: "Jersey (+44-1534)", mask: "xxxxxxxxx" },
    { code: "+962", country: "JO", label: "Jordan (+962)", mask: "7xxxxxxxx" },
    { code: "+7", country: "KZ", label: "Kazakhstan (+7)", mask: "7xxxxxxxxx" },
    { code: "+254", country: "KE", label: "Kenya (+254)", mask: "7xxxxxxxx" },
    { code: "+686", country: "KI", label: "Kiribati (+686)", mask: "xxxxxxxxx" },
    { code: "+383", country: "XK", label: "Kosovo (+383)", mask: "xxxxxxxxx" },
    { code: "+965", country: "KW", label: "Kuwait (+965)", mask: "xxxxxxxxx" },
    { code: "+996", country: "KG", label: "Kyrgyzstan (+996)", mask: "xxxxxxxxx" },
    { code: "+856", country: "LA", label: "Laos (+856)", mask: "xxxxxxxxx" },
    { code: "+371", country: "LV", label: "Latvia (+371)", mask: "2xxxxxxx" },
    { code: "+961", country: "LB", label: "Lebanon (+961)", mask: "3xxxxxxx" },
    { code: "+266", country: "LS", label: "Lesotho (+266)", mask: "xxxxxxxxx" },
    { code: "+231", country: "LR", label: "Liberia (+231)", mask: "xxxxxxxxx" },
    { code: "+218", country: "LY", label: "Libya (+218)", mask: "9xxxxxxxx" },
    { code: "+423", country: "LI", label: "Liechtenstein (+423)", mask: "xxxxxxxxx" },
    { code: "+370", country: "LT", label: "Lithuania (+370)", mask: "6xxxxxxx" },
    { code: "+352", country: "LU", label: "Luxembourg (+352)", mask: "6xxxxxxxx" },
    { code: "+853", country: "MO", label: "Macau (+853)", mask: "xxxxxxxxx" },
    { code: "+389", country: "MK", label: "Macedonia (+389)", mask: "7xxxxxxx" },
    { code: "+261", country: "MG", label: "Madagascar (+261)", mask: "xxxxxxxxx" },
    { code: "+265", country: "MW", label: "Malawi (+265)", mask: "xxxxxxxxx" },
    { code: "+60", country: "MY", label: "Malaysia (+60)", mask: "1xxxxxxxxx" },
    { code: "+960", country: "MV", label: "Maldives (+960)", mask: "xxxxxxxxx" },
    { code: "+223", country: "ML", label: "Mali (+223)", mask: "xxxxxxxxx" },
    { code: "+356", country: "MT", label: "Malta (+356)", mask: "xxxxxxxxx" },
    { code: "+692", country: "MH", label: "Marshall Islands (+692)", mask: "xxxxxxxxx" },
    { code: "+222", country: "MR", label: "Mauritania (+222)", mask: "xxxxxxxxx" },
    { code: "+230", country: "MU", label: "Mauritius (+230)", mask: "xxxxxxxxx" },
    { code: "+262", country: "YT", label: "Mayotte (+262)", mask: "xxxxxxxxx" },
    { code: "+52", country: "MX", label: "Mexico (+52)", mask: "1xxxxxxxxx" },
    { code: "+691", country: "FM", label: "Micronesia (+691)", mask: "xxxxxxxxx" },
    { code: "+373", country: "MD", label: "Moldova (+373)", mask: "xxxxxxxxx" },
    { code: "+377", country: "MC", label: "Monaco (+377)", mask: "xxxxxxxxx" },
    { code: "+976", country: "MN", label: "Mongolia (+976)", mask: "xxxxxxxxx" },
    { code: "+382", country: "ME", label: "Montenegro (+382)", mask: "6xxxxxxx" },
    { code: "+1-664", country: "MS", label: "Montserrat (+1-664)", mask: "xxxxxxxxx" },
    { code: "+212", country: "MA", label: "Morocco (+212)", mask: "6xxxxxxxx" },
    { code: "+258", country: "MZ", label: "Mozambique (+258)", mask: "xxxxxxxxx" },
    { code: "+95", country: "MM", label: "Myanmar (+95)", mask: "xxxxxxxxx" },
    { code: "+264", country: "NA", label: "Namibia (+264)", mask: "xxxxxxxxx" },
    { code: "+674", country: "NR", label: "Nauru (+674)", mask: "xxxxxxxxx" },
    { code: "+977", country: "NP", label: "Nepal (+977)", mask: "98xxxxxxxx" },
    { code: "+31", country: "NL", label: "Netherlands (+31)", mask: "6xxxxxxxx" },
    { code: "+599", country: "AN", label: "Netherlands Antilles (+599)", mask: "xxxxxxxxx" },
    { code: "+687", country: "NC", label: "New Caledonia (+687)", mask: "xxxxxxxxx" },
    { code: "+64", country: "NZ", label: "New Zealand (+64)", mask: "2xxxxxxxxx" },
    { code: "+505", country: "NI", label: "Nicaragua (+505)", mask: "xxxxxxxxx" },
    { code: "+227", country: "NE", label: "Niger (+227)", mask: "xxxxxxxxx" },
    { code: "+234", country: "NG", label: "Nigeria (+234)", mask: "xxxxxxxxxx" },
    { code: "+683", country: "NU", label: "Niue (+683)", mask: "xxxxxxxxx" },
    { code: "+672", country: "NF", label: "Norfolk Island (+672)", mask: "xxxxxxxxx" },
    { code: "+850", country: "KP", label: "North Korea (+850)", mask: "xxxxxxxxx" },
    { code: "+1-670", country: "MP", label: "Northern Mariana Islands (+1-670)", mask: "xxxxxxxxx" },
    { code: "+47", country: "NO", label: "Norway (+47)", mask: "9xxxxxxx" },
    { code: "+968", country: "OM", label: "Oman (+968)", mask: "9xxxxxxx" },
    { code: "+92", country: "PK", label: "Pakistan (+92)", mask: "3xxxxxxxxx" },
    { code: "+680", country: "PW", label: "Palau (+680)", mask: "xxxxxxxxx" },
    { code: "+970", country: "PS", label: "Palestine (+970)", mask: "5xxxxxxx" },
    { code: "+507", country: "PA", label: "Panama (+507)", mask: "xxxxxxxxx" },
    { code: "+675", country: "PG", label: "Papua New Guinea (+675)", mask: "xxxxxxxxx" },
    { code: "+595", country: "PY", label: "Paraguay (+595)", mask: "xxxxxxxxx" },
    { code: "+51", country: "PE", label: "Peru (+51)", mask: "9xxxxxxxx" },
    { code: "+63", country: "PH", label: "Philippines (+63)", mask: "9xxxxxxxxx" },
    { code: "+64", country: "PN", label: "Pitcairn (+64)", mask: "xxxxxxxxx" },
    { code: "+48", country: "PL", label: "Poland (+48)", mask: "xxxxxxxxx" },
    { code: "+351", country: "PT", label: "Portugal (+351)", mask: "9xxxxxxxx" },
    { code: "+1-787", country: "PR", label: "Puerto Rico (+1-787)", mask: "xxxxxxxxx" },
    { code: "+974", country: "QA", label: "Qatar (+974)", mask: "xxxxxxxx" },
    { code: "+242", country: "CG", label: "Republic of the Congo (+242)", mask: "xxxxxxxxx" },
    { code: "+262", country: "RE", label: "Reunion (+262)", mask: "xxxxxxxxx" },
    { code: "+40", country: "RO", label: "Romania (+40)", mask: "7xxxxxxxxx" },
    { code: "+7", country: "RU", label: "Russia (+7)", mask: "9xxxxxxxxx" },
    { code: "+250", country: "RW", label: "Rwanda (+250)", mask: "xxxxxxxxx" },
    { code: "+590", country: "BL", label: "Saint Barthelemy (+590)", mask: "xxxxxxxxx" },
    { code: "+290", country: "SH", label: "Saint Helena (+290)", mask: "xxxxxxxxx" },
    { code: "+1-869", country: "KN", label: "Saint Kitts and Nevis (+1-869)", mask: "xxxxxxxxx" },
    { code: "+1-758", country: "LC", label: "Saint Lucia (+1-758)", mask: "xxxxxxxxx" },
    { code: "+590", country: "MF", label: "Saint Martin (+590)", mask: "xxxxxxxxx" },
    { code: "+508", country: "PM", label: "Saint Pierre and Miquelon (+508)", mask: "xxxxxxxxx" },
    { code: "+1-784", country: "VC", label: "Saint Vincent and the Grenadines (+1-784)", mask: "xxxxxxxxx" },
    { code: "+685", country: "WS", label: "Samoa (+685)", mask: "xxxxxxxxx" },
    { code: "+378", country: "SM", label: "San Marino (+378)", mask: "xxxxxxxxx" },
    { code: "+239", country: "ST", label: "Sao Tome and Principe (+239)", mask: "xxxxxxxxx" },
    { code: "+966", country: "SA", label: "Saudi Arabia (+966)", mask: "5xxxxxxxx" },
    { code: "+221", country: "SN", label: "Senegal (+221)", mask: "xxxxxxxxx" },
    { code: "+381", country: "RS", label: "Serbia (+381)", mask: "6xxxxxxx" },
    { code: "+248", country: "SC", label: "Seychelles (+248)", mask: "xxxxxxxxx" },
    { code: "+232", country: "SL", label: "Sierra Leone (+232)", mask: "xxxxxxxxx" },
    { code: "+65", country: "SG", label: "Singapore (+65)", mask: "xxxxxxxxx" },
    { code: "+1-721", country: "SX", label: "Sint Maarten (+1-721)", mask: "xxxxxxxxx" },
    { code: "+421", country: "SK", label: "Slovakia (+421)", mask: "9xx xxx xxx" },
    { code: "+386", country: "SI", label: "Slovenia (+386)", mask: "xxxxxxxx" },
    { code: "+677", country: "SB", label: "Solomon Islands (+677)", mask: "xxxxxxxxx" },
    { code: "+252", country: "SO", label: "Somalia (+252)", mask: "xxxxxxxxx" },
    { code: "+27", country: "ZA", label: "South Africa (+27)", mask: "xxxxxxxxx" },
    { code: "+82", country: "KR", label: "South Korea (+82)", mask: "10xxxxxxxx" },
    { code: "+211", country: "SS", label: "South Sudan (+211)", mask: "xxxxxxxxx" },
    { code: "+34", country: "ES", label: "Spain (+34)", mask: "6xxxxxxxx" },
    { code: "+94", country: "LK", label: "Sri Lanka (+94)", mask: "7xxxxxxxx" },
    { code: "+249", country: "SD", label: "Sudan (+249)", mask: "xxxxxxxxx" },
    { code: "+597", country: "SR", label: "Suriname (+597)", mask: "xxxxxxxxx" },
    { code: "+47", country: "SJ", label: "Svalbard and Jan Mayen (+47)", mask: "xxxxxxxxx" },
    { code: "+268", country: "SZ", label: "Swaziland (+268)", mask: "xxxxxxxxx" },
    { code: "+46", country: "SE", label: "Sweden (+46)", mask: "7xxxxxxxx" },
    { code: "+41", country: "CH", label: "Switzerland (+41)", mask: "7xxxxxxxxx" },
    { code: "+963", country: "SY", label: "Syria (+963)", mask: "9xxxxxxxx" },
    { code: "+886", country: "TW", label: "Taiwan (+886)", mask: "9xxxxxxxx" },
    { code: "+992", country: "TJ", label: "Tajikistan (+992)", mask: "xxxxxxxxx" },
    { code: "+255", country: "TZ", label: "Tanzania (+255)", mask: "xxxxxxxxx" },
    { code: "+66", country: "TH", label: "Thailand (+66)", mask: "8xxxxxxxxx" },
    { code: "+228", country: "TG", label: "Togo (+228)", mask: "xxxxxxxxx" },
    { code: "+690", country: "TK", label: "Tokelau (+690)", mask: "xxxxxxxxx" },
    { code: "+676", country: "TO", label: "Tonga (+676)", mask: "xxxxxxxxx" },
    { code: "+1-868", country: "TT", label: "Trinidad and Tobago (+1-868)", mask: "xxxxxxxxx" },
    { code: "+216", country: "TN", label: "Tunisia (+216)", mask: "xxxxxxxxx" },
    { code: "+90", country: "TR", label: "Turkey (+90)", mask: "5xxxxxxxxx" },
    { code: "+993", country: "TM", label: "Turkmenistan (+993)", mask: "xxxxxxxxx" },
    { code: "+1-649", country: "TC", label: "Turks and Caicos Islands (+1-649)", mask: "xxxxxxxxx" },
    { code: "+688", country: "TV", label: "Tuvalu (+688)", mask: "xxxxxxxxx" },
    { code: "+1-340", country: "VI", label: "U.S. Virgin Islands (+1-340)", mask: "xxxxxxxxx" },
    { code: "+256", country: "UG", label: "Uganda (+256)", mask: "xxxxxxxxx" },
    { code: "+380", country: "UA", label: "Ukraine (+380)", mask: "xxxxxxxxx" },
    { code: "+971", country: "AE", label: "United Arab Emirates (+971)", mask: "5xxxxxxxx" },
    { code: "+44", country: "GB", label: "United Kingdom (+44)", mask: "7xxxxxxxxx" },
    { code: "+1", country: "US", label: "United States (+1)", mask: "xxxxxxxxxx" },
    { code: "+598", country: "UY", label: "Uruguay (+598)", mask: "xxxxxxxxx" },
    { code: "+998", country: "UZ", label: "Uzbekistan (+998)", mask: "xxxxxxxxx" },
    { code: "+678", country: "VU", label: "Vanuatu (+678)", mask: "xxxxxxxxx" },
    { code: "+379", country: "VA", label: "Vatican (+379)", mask: "xxxxxxxxx" },
    { code: "+58", country: "VE", label: "Venezuela (+58)", mask: "xxxxxxxxx" },
    { code: "+84", country: "VN", label: "Vietnam (+84)", mask: "9xxxxxxxxx" },
    { code: "+681", country: "WF", label: "Wallis and Futuna (+681)", mask: "xxxxxxxxx" },
    { code: "+212", country: "EH", label: "Western Sahara (+212)", mask: "xxxxxxxxx" },
    { code: "+967", country: "YE", label: "Yemen (+967)", mask: "7xxxxxxxx" },
    { code: "+260", country: "ZM", label: "Zambia (+260)", mask: "xxxxxxxxx" },
    { code: "+263", country: "ZW", label: "Zimbabwe (+263)", mask: "xxxxxxxxx" }
];
